backend:
  name: git-gateway
  repo: csmaller/motive8
  branch: main # Branch to update (optional; defaults to master)

media_folder: /public/img
public_folder: /img

collections:
  - name: 'events_calendar'
    label: 'Events Calendar'
    extension: 'json'

    files:
      - file: 'content/json/events.json'
        label: 'Events'
        name: 'eventList'
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - { name: title }
              - {
                  label: 'Single Event',
                  name: date,
                  widget: datetime,
                  required: false,
                }

              - { name: description }
              - {
                  label: 'Reoccuring Days Of Week (select for reoccuring events)',
                  name: 'days_of_week',
                  required: false,
                  widget: 'select',
                  multiple: true,
                  options:
                    [
                      { label: 'Sunday', value: '0' },
                      { label: 'Monday', value: '1' },
                      { label: 'Tues', value: '2' },
                      { label: 'Wed', value: '3' },
                      { label: 'Thur', value: '4' },
                      { label: 'Fri', value: '5' },
                      { label: 'Sat', value: '6' },
                    ],
                }
              - {
                  label: 'Reoccuring Event Start (only for reoccuring events)',
                  name: event_start_time,
                  widget: time,
                  required: false,
                }
              - {
                  label: 'Reoccuring Event End (only for reoccuring events)',
                  name: event_start_end,
                  widget: time,
                  required: false,
                }

  - name: 'blog'
    label: 'News And Events'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          default: 'img',
          reqiured: false,
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Event Date', name: 'event_date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
          label: 'Payment Link',
          name: 'link',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'about'
    label: 'About'
    folder: 'content/about'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'mission'
    label: 'Mission'
    folder: 'content/mission'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'coaches'
    label: 'Coaches'
    folder: 'content/coaches'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Phone', name: 'phone', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'programs'
    label: 'Programs'
    folder: 'content/programs'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Background Color',
          name: 'background_color',
          widget: 'select',
          options:
            [
              { label: 'White', value: 'rgba(255,255,255, .8)' },
              { label: 'Blue', value: 'rgba(57, 121, 192, 0.8)' },
              { label: 'Yellow', value: 'rgba(236, 202, 81, 0.8)' },
            ],
        }
      - { label: 'Payment Link', name: 'link', widget: 'string' }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
          default: 'img',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'merchandise'
    label: 'Merchandise'
    folder: 'content/store'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Background Color',
          name: 'background_color',
          widget: 'select',
          options:
            [
              { label: 'White', value: 'rgba(255,255,255, .8)' },
              { label: 'Blue', value: 'rgba(57, 121, 192, 0.8)' },
              { label: 'Yellow', value: 'rgba(236, 202, 81, 0.8)' },
            ],
        }
      - { label: 'Payment Link', name: 'link', widget: 'string' }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
          default: 'img',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'images'
    extension: 'json'
    label: 'Image Slider'
    files:
      - file: 'public/json/images.json'
        label: 'Image Slider'
        name: 'imageList'
        fields:
          - name: images
            label: images
            widget: list
            summary: “{{fields.image}}”
            fields:
              - { label: “Image”, name: image, widget: image }

  - name: 'classes'
    label: 'Classes'
    folder: 'content/classes'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
