backend:
  name: git-gateway
  repo: csmaller/motive8
  branch: main # Branch to update (optional; defaults to master)

media_folder: /public/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'News And Events'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'about'
    label: 'About'
    folder: 'content/about'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'mission'
    label: 'Mission'
    folder: 'content/mission'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'coaches'
    label: 'Coaches'
    folder: 'content/coaches'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Phone', name: 'phone', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'programs'
    label: 'Programs'
    folder: 'content/programs'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Background Color',
          name: 'background_color',
          widget: 'select',
          options:
            [
              { label: 'Transparent', value: 'transparent' },
              { label: 'White', value: 'rgba(255,255,255, .8)' },
              { label: 'Blue', value: 'rgba(57, 121, 192, 0.8)' },
              { label: 'Yellow', value: 'rgba(236, 202, 81, 0.8)' },
            ],
        }
      - { label: 'Payment Link', name: 'link', widget: 'string' }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
          default: 'img',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'classes'
    label: 'Classes'
    folder: 'content/classes'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
