backend:
  name: git-gateway
  repo: csmaller/motive8
  branch: main # Branch to update (optional; defaults to master)

media_folder: /public/img
public_folder: /img

collections:
  - name: 'events_calendar'
    label: 'Events Calendar'
    extension: 'json'

    files:
      - file: 'content/json/events.json'
        label: 'Events'
        name: 'eventList'
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - { name: title }
              - {
                  label: 'Reoccuring Days Of the Week (for reoccuring events only)',
                  name: 'days_of_week',
                  widget: 'select',
                  required: false,
                  multiple: true,
                  options:
                    [
                      { label: 'Sun', value: 0 },
                      { label: 'Mon', value: 1 },
                      { label: 'Tues', value: 2 },
                      { label: 'Wed', value: 3 },
                      { label: 'Thur', value: 4 },
                      { label: 'Fri', value: 5 },
                      { label: 'Sat', value: 6 },
                    ],
                }
              - {
                  label: 'Is Reoccuring Event? (make sure days of week are selected)',
                  name: 'reoccuring',
                  widget: 'boolean',
                  default: false,
                  required: false,
                }
              - {
                  label: 'Is All Day Event? (nullifies the time set)',
                  name: 'all_day',
                  widget: 'boolean',
                  default: false,
                  required: false,
                }
              - { name: payment_link, required: false }
              - { name: description, label: 'Description' }
              - { label: 'Event Details', name: 'body', widget: 'markdown' }
              - {
                  label: 'Event Start Date/Time',
                  name: event_start_time,
                  widget: datetime,
                }
              - {
                  label: 'Event End Date/Time (do not need for indefinite reoccuring events)',
                  name: event_end_time,
                  widget: datetime,
                }

  - name: 'blog'
    label: 'News And Events'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Ad Start Date', name: 'start', widget: 'datetime' }
      - { label: 'Ad End Date', name: 'end', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Main Header Image',
          name: 'image',
          widget: 'image',
          required: true,
        }

      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          default: 'img',
          reqiured: false,
        }
      - {
          label: 'Background Color',
          name: 'background_color',
          widget: 'select',
          options:
            [
              { label: 'None', value: '' },
              { label: 'White', value: 'rgba(255,255,255, .8)' },
              { label: 'Blue', value: 'rgba(57, 121, 192, 0.8)' },
              { label: 'Yellow', value: 'rgba(236, 202, 81, 0.8)' },
            ],
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Event Start Date',
          name: 'event_date_start',
          widget: 'datetime',
        }
      - { label: 'Event End Date', name: 'event_date_end', widget: 'datetime' }
      - { label: 'Sub Header', name: 'description', widget: 'string' }
      - {
          label: 'Payment Link',
          name: 'link',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'about'
    label: 'About'
    folder: 'content/about'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'mission'
    label: 'Mission'
    folder: 'content/mission'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'coaches'
    label: 'Coaches'
    folder: 'content/coaches'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          required: false,
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Phone', name: 'phone', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'programs'
    label: 'Programs'
    folder: 'content/programs'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Background Color',
          name: 'background_color',
          widget: 'select',
          options:
            [
              { label: 'White', value: 'rgba(255,255,255, .8)' },
              { label: 'Blue', value: 'rgba(57, 121, 192, 0.8)' },
              { label: 'Yellow', value: 'rgba(236, 202, 81, 0.8)' },
            ],
        }
      - { label: 'Payment Link', name: 'link', widget: 'string' }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
          default: 'img',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'merchandise'
    label: 'Merchandise'
    folder: 'content/store'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Stripe ID', name: 'id', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }

      - { label: 'Price', name: 'price', widget: 'number', value_type: 'float' }
      - { label: 'Payment Link', name: 'link', widget: 'string' }
      - {
          label: 'Image Class',
          name: 'class',
          widget: 'string',
          reqiured: false,
          default: 'img',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'images'
    extension: 'json'
    label: 'Image Slider'
    files:
      - file: 'public/json/images.json'
        label: 'Image Slider'
        name: 'imageList'
        fields:
          - name: images
            label: images
            widget: list
            summary: “{{fields.image}}”
            fields:
              - { label: “Image”, name: image, widget: image }

  - name: 'classes'
    label: 'Classes'
    folder: 'content/classes'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
